FROM basty149/visual-studio-code:1.83.1

USER root

RUN apt-get update && \
    apt-get install -y python3 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER vscode

COPY --chown=vscode:vscode ms-python.python-2023.19.12860613.vsix /tmp/python.vsix

RUN code --install-extension /tmp/python.vsix && \
    rm /tmp/python.vsix



