FROM basty149/visual-studio-code:1.83.1

USER root

RUN apt-get update && \
    apt-get install -y python3 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER vscode

RUN wget -O /tmp/python.vsix.gz https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-python/vsextensions/python/2023.19.12860613/vspackage && \
    gunzip /tmp/python.vsix.gz && \
    code --install-extension /tmp/python.vsix && \
    rm /tmp/python.vsix



