name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore: 
      README.md
  pull_request:
    branches: [ "main" ]
    paths-ignore: 
      README.md
  workflow_dispatch:
    inputs:
      

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push VISUAL STUDIO CODE BASE
      uses: docker/build-push-action@v5
      with:
          context: .
          push: true
          tags: basty149/visual-studio-code:1.83.1
          file: Dockerfile-debian-base